# Generated by Django 5.0.1 on 2026-01-04 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_concepts', models.IntegerField(default=0)),
                ('total_relationships', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('top_concepts', models.JSONField(default=list, help_text='Most connected concepts')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Knowledge Graph',
                'verbose_name_plural': 'User Knowledge Graphs',
            },
        ),
        migrations.CreateModel(
            name='ConceptEvolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_concepts', models.JSONField(help_text='Snapshot of related concepts')),
                ('understanding_depth', models.IntegerField(default=1, help_text='How many times encountered')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='analysis.concept')),
                ('document', models.ForeignKey(help_text='Document that updated understanding', on_delete=django.db.models.deletion.CASCADE, to='ingestion.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_evolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['concept', 'timestamp'],
                'indexes': [models.Index(fields=['user', 'concept', 'timestamp'], name='graph_conce_user_id_9c42c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('related', 'Related Topic'), ('subtopic', 'Subtopic Of'), ('contradicts', 'Contradicts'), ('supports', 'Supports')], default='related', max_length=50)),
                ('strength', models.FloatField(default=0.0, help_text='How strongly related (0-1)')),
                ('co_occurrence_count', models.IntegerField(default=0, help_text='How many docs have both')),
                ('weighted_strength', models.FloatField(default=0.0, help_text='Strength adjusted for source quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='analysis.concept')),
                ('concept_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='analysis.concept')),
            ],
            options={
                'indexes': [models.Index(fields=['concept_a', '-strength'], name='graph_conce_concept_ae60bb_idx'), models.Index(fields=['concept_b', '-strength'], name='graph_conce_concept_8d1ec8_idx')],
                'unique_together': {('concept_a', 'concept_b', 'relationship_type')},
            },
        ),
    ]
