# Generated by Django 5.0.1 on 2026-01-04 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF Document'), ('markdown', 'Markdown'), ('text', 'Plain Text'), ('web', 'Web Article'), ('social', 'Social Media Post')], max_length=20)),
                ('source_type', models.CharField(choices=[('upload', 'User Upload'), ('paste', 'User Paste'), ('url', 'URL Fetch'), ('extension', 'Browser Extension')], max_length=20)),
                ('raw_content', models.TextField(help_text='Original unprocessed content')),
                ('normalized_content', models.TextField(blank=True, help_text='Cleaned and normalized text')),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('source_name', models.CharField(blank=True, help_text='e.g., Twitter, Medium, etc.', max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When user added this content')),
                ('word_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('estimated_read_time', models.IntegerField(default=0, help_text='In minutes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('chunk_index', models.IntegerField(help_text='Position in document')),
                ('word_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('embedding_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=200)),
                ('post_url', models.URLField(max_length=2000)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('shares_count', models.IntegerField(blank=True, null=True)),
                ('is_thread', models.BooleanField(default=False)),
                ('thread_position', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_metadata', to='ingestion.document')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-ingested_at'], name='ingestion_d_user_id_f80595_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type'], name='ingestion_d_content_0089b3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_processed'], name='ingestion_d_is_proc_7e8e22_idx'),
        ),
        migrations.AddIndex(
            model_name='contentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='ingestion_c_documen_c1b05f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
