# Generated by Django 5.0.1 on 2026-01-04 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('document_count', models.IntegerField(default=0, help_text='How many documents mention this')),
                ('total_mentions', models.IntegerField(default=0, help_text='Total times mentioned across all docs')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-document_count', '-total_mentions'],
                'indexes': [models.Index(fields=['normalized_name'], name='analysis_co_normali_54c5dc_idx'), models.Index(fields=['-document_count'], name='analysis_co_documen_cb309b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(help_text='Cleaned version for comparison')),
                ('claim_type', models.CharField(choices=[('factual', 'Factual Statement'), ('opinion', 'Opinion'), ('prediction', 'Prediction'), ('statistic', 'Statistic/Number')], default='factual', max_length=50)),
                ('surrounding_context', models.TextField(blank=True, help_text='Text around this claim')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in extraction (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ingestion.contentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ingestion.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='analysis_cl_documen_cc52f4_idx'), models.Index(fields=['claim_type'], name='analysis_cl_claim_t_5b8457_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_count', models.IntegerField(default=1)),
                ('relevance_score', models.FloatField(default=0.0, help_text='How central is this concept (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='analysis.concept')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='ingestion.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', '-relevance_score'], name='analysis_do_documen_59c9d6_idx'), models.Index(fields=['concept', '-mention_count'], name='analysis_do_concept_da3ae0_idx')],
                'unique_together': {('document', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.JSONField(help_text='Embedding vector as list of floats')),
                ('model_name', models.CharField(help_text='Which model generated this', max_length=100)),
                ('vector_dimension', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='ingestion.contentchunk')),
            ],
            options={
                'indexes': [models.Index(fields=['chunk'], name='analysis_em_chunk_i_2a7088_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmotionalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('outrage', 'Outrage Bait'), ('fear', 'Fear-Mongering'), ('urgency', 'False Urgency'), ('clickbait', 'Clickbait Language'), ('hyperbole', 'Hyperbole')], max_length=50)),
                ('matched_phrases', models.JSONField(help_text='List of phrases that triggered detection')),
                ('context', models.TextField(help_text='Surrounding text for transparency')),
                ('intensity_score', models.FloatField(help_text='How strong is this pattern (0-1)')),
                ('explanation', models.TextField(help_text='Why this was flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_patterns', to='ingestion.document')),
            ],
            options={
                'ordering': ['-intensity_score'],
                'indexes': [models.Index(fields=['document', 'pattern_type'], name='analysis_em_documen_bdbe7a_idx')],
            },
        ),
    ]
