# Generated by Django 5.0.1 on 2026-01-04 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContradictionDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_a_id', models.UUIDField(help_text='Claim from document A')),
                ('claim_b_id', models.UUIDField(help_text='Claim from document B')),
                ('claim_a_text', models.TextField()),
                ('claim_b_text', models.TextField()),
                ('confidence_score', models.FloatField(help_text='How confident we are (0-1)')),
                ('explanation', models.TextField(help_text='Why these are contradictory')),
                ('user_confirmed', models.BooleanField(blank=True, help_text='User says this is a real contradiction', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('document_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions_as_a', to='ingestion.document')),
                ('document_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions_as_b', to='ingestion.document')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='scoring_con_detecte_942046_idx'), models.Index(fields=['document_a'], name='scoring_con_documen_137327_idx'), models.Index(fields=['document_b'], name='scoring_con_documen_ada72a_idx')],
                'unique_together': {('document_a', 'document_b', 'claim_a_id', 'claim_b_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('novelty_score', models.FloatField(default=0.0, help_text='How much new information')),
                ('depth_score', models.FloatField(default=0.0, help_text='How substantive/detailed')),
                ('redundancy_score', models.FloatField(default=0.0, help_text='How much repetition')),
                ('cognitive_load_score', models.FloatField(default=0.0, help_text='Mental effort required')),
                ('overall_value_score', models.FloatField(default=0.0, help_text='Weighted combination')),
                ('novelty_explanation', models.TextField(blank=True)),
                ('depth_explanation', models.TextField(blank=True)),
                ('redundancy_explanation', models.TextField(blank=True)),
                ('cognitive_load_explanation', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='ingestion.document')),
            ],
            options={
                'ordering': ['-overall_value_score'],
                'indexes': [models.Index(fields=['-novelty_score'], name='scoring_doc_novelty_70812d_idx'), models.Index(fields=['-overall_value_score'], name='scoring_doc_overall_8532be_idx')],
            },
        ),
        migrations.CreateModel(
            name='RedundancyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(help_text='Cosine similarity (0-1)')),
                ('overlap_percentage', models.FloatField(help_text='% of concepts that overlap')),
                ('repeated_concepts', models.JSONField(help_text='List of concept names that appear in both')),
                ('repeated_claims', models.JSONField(default=list, help_text='List of similar claim IDs')),
                ('explanation', models.TextField(help_text='User-facing explanation of redundancy')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redundancies', to='ingestion.document')),
                ('similar_to', models.ForeignKey(help_text='Earlier document with similar content', on_delete=django.db.models.deletion.CASCADE, related_name='repeated_in', to='ingestion.document')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['document', '-similarity_score'], name='scoring_red_documen_0777da_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_documents', models.IntegerField(default=0)),
                ('total_words_read', models.IntegerField(default=0)),
                ('total_read_time', models.IntegerField(default=0, help_text='Minutes')),
                ('avg_novelty_score', models.FloatField(default=0.0)),
                ('avg_depth_score', models.FloatField(default=0.0)),
                ('avg_redundancy_score', models.FloatField(default=0.0)),
                ('avg_cognitive_load', models.FloatField(default=0.0)),
                ('redundancies_detected', models.IntegerField(default=0)),
                ('contradictions_detected', models.IntegerField(default=0)),
                ('emotional_patterns_detected', models.IntegerField(default=0)),
                ('top_concepts', models.JSONField(default=list, help_text='List of most frequent concepts')),
                ('novel_concepts_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='Generated summary for user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user', '-period_end'], name='scoring_use_user_id_e20f0e_idx'), models.Index(fields=['period_type', 'period_start'], name='scoring_use_period__3894d4_idx')],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
    ]
